name: Docker Image CI

env:
  TAG: $(date +%s)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file dockerfile --tag iampgr4/diabotical-wer-discord-bot:${{TAG}}
    - name: Push the Docker image
      run: docker push iampgr4/diabotical-wer-discord-bot:${{TAG}}